## For WOW Dataset, ReSee (Sep.) Model
# CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset WOW --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 8 --do_sample --test_iter 5000 --model_type t5 --max_val_batches 100 --num_train_epochs 30 --max_seq_length 185 --max_seq_a_length 35 --max_episode_length 1 --add_textual_ent &&\
# CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset WOW --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 8 --do_sample --test_iter 5000 --model_type t5 --max_val_batches 100 --num_train_epochs 30 --max_seq_length 185 --max_seq_a_length 35 --max_episode_length 1 --no_ent_vis &&\
# CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset WOW --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 8 --do_sample --test_iter 5000 --model_type t5 --max_val_batches 100 --num_train_epochs 30 --max_seq_length 185 --max_seq_a_length 35 --max_episode_length 1 --no_turn_vis --add_textual_ent &&\
# CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset WOW --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 8 --do_sample --test_iter 5000 --model_type t5 --max_val_batches 100 --num_train_epochs 30 --max_seq_length 185 --max_seq_a_length 35 --max_episode_length 1 --no_ent_vis --no_turn_vis

## For DD Dataset, ReSee (Sep.) Model
# CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset DD --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 6 --do_sample --test_iter 5000 --model_type t5 --max_val_batches 100 --num_train_epochs 25 --max_seq_length 175 --max_seq_a_length 35 --max_episode_length 1 --add_textual_ent &&\
# CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset DD --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 6 --do_sample --test_iter 5000 --model_type t5 --max_val_batches 100 --num_train_epochs 25 --max_seq_length 175 --max_seq_a_length 35 --max_episode_length 1 --no_ent_vis &&\
# CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset DD --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 6 --do_sample --test_iter 5000 --model_type t5 --max_val_batches 100 --num_train_epochs 25 --max_seq_length 175 --max_seq_a_length 35 --max_episode_length 1 --no_turn_vis --add_textual_ent &&\
# CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset DD --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 6 --do_sample --test_iter 5000 --model_type t5 --max_val_batches 100 --num_train_epochs 25 --max_seq_length 175 --max_seq_a_length 35 --max_episode_length 1 --no_ent_vis --no_turn_vis

## For WOW Dataset, ReSee (Share.) Model
# CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset WOW --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 8 --do_sample --test_iter 5000 --model_type unilm --max_val_batches 100 --num_train_epochs 30 --max_seq_length 185 --max_seq_a_length 35 --max_episode_length 1 --add_textual_ent &&\
# CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset WOW --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 8 --do_sample --test_iter 5000 --model_type unilm --max_val_batches 100 --num_train_epochs 30 --max_seq_length 185 --max_seq_a_length 35 --max_episode_length 1 --no_ent_vis &&\
# CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset WOW --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 8 --do_sample --test_iter 5000 --model_type unilm --max_val_batches 100 --num_train_epochs 30 --max_seq_length 185 --max_seq_a_length 35 --max_episode_length 1 --no_turn_vis --add_textual_ent &&\
# CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset WOW --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 8 --do_sample --test_iter 5000 --model_type unilm --max_val_batches 100 --num_train_epochs 30 --max_seq_length 185 --max_seq_a_length 35 --max_episode_length 1 --no_ent_vis --no_turn_vis

## For DD Dataset, ReSee (Share.) Model
CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset DD --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 6 --do_sample --test_iter 5000 --model_type unilm --max_val_batches 100 --num_train_epochs 25 --max_seq_length 175 --max_seq_a_length 35 --max_episode_length 1 --add_textual_ent &&\
CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset DD --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 6 --do_sample --test_iter 5000 --model_type unilm --max_val_batches 100 --num_train_epochs 25 --max_seq_length 175 --max_seq_a_length 35 --max_episode_length 1 --no_ent_vis &&\
CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset DD --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 6 --do_sample --test_iter 5000 --model_type unilm --max_val_batches 100 --num_train_epochs 25 --max_seq_length 175 --max_seq_a_length 35 --max_episode_length 1 --no_turn_vis --add_textual_ent &&\
CUDA_VISIBLE_DEVICES=0 python3 run.py --do_train --dataset DD --history_in_context --img_add_pos concat --log_epoch 5 --per_gpu_train_batch_size 12 --learning_rate 5e-3 --max_ent_img_seq_length 6 --do_sample --test_iter 5000 --model_type unilm --max_val_batches 100 --num_train_epochs 25 --max_seq_length 175 --max_seq_a_length 35 --max_episode_length 1 --no_ent_vis --no_turn_vis